include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  errors:
    file_names: ignore

linter:
  rules:
    camel_case_types: true
    prefer_void_to_null: true
    void_checks: true
    omit_local_variable_types: false
    prefer_single_quotes: false
